/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bk.thesis.data.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-07-20")
public class TRawReview implements org.apache.thrift.TBase<TRawReview, TRawReview._Fields>, java.io.Serializable, Cloneable, Comparable<TRawReview> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TRawReview");

  private static final org.apache.thrift.protocol.TField REVIEW_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("reviewId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField REVIEW_FIELD_DESC = new org.apache.thrift.protocol.TField("review", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TITLE_FIELD_DESC = new org.apache.thrift.protocol.TField("title", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField RATING_FIELD_DESC = new org.apache.thrift.protocol.TField("rating", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField CREATED_DTTM_FIELD_DESC = new org.apache.thrift.protocol.TField("createdDttm", org.apache.thrift.protocol.TType.I64, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TRawReviewStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TRawReviewTupleSchemeFactory();

  public java.lang.String reviewId; // required
  public java.lang.String review; // required
  public java.lang.String title; // required
  public int rating; // required
  public long createdDttm; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REVIEW_ID((short)1, "reviewId"),
    REVIEW((short)2, "review"),
    TITLE((short)3, "title"),
    RATING((short)4, "rating"),
    CREATED_DTTM((short)5, "createdDttm");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REVIEW_ID
          return REVIEW_ID;
        case 2: // REVIEW
          return REVIEW;
        case 3: // TITLE
          return TITLE;
        case 4: // RATING
          return RATING;
        case 5: // CREATED_DTTM
          return CREATED_DTTM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RATING_ISSET_ID = 0;
  private static final int __CREATEDDTTM_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REVIEW_ID, new org.apache.thrift.meta_data.FieldMetaData("reviewId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REVIEW, new org.apache.thrift.meta_data.FieldMetaData("review", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TITLE, new org.apache.thrift.meta_data.FieldMetaData("title", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RATING, new org.apache.thrift.meta_data.FieldMetaData("rating", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CREATED_DTTM, new org.apache.thrift.meta_data.FieldMetaData("createdDttm", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TRawReview.class, metaDataMap);
  }

  public TRawReview() {
  }

  public TRawReview(
    java.lang.String reviewId,
    java.lang.String review,
    java.lang.String title,
    int rating,
    long createdDttm)
  {
    this();
    this.reviewId = reviewId;
    this.review = review;
    this.title = title;
    this.rating = rating;
    setRatingIsSet(true);
    this.createdDttm = createdDttm;
    setCreatedDttmIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TRawReview(TRawReview other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetReviewId()) {
      this.reviewId = other.reviewId;
    }
    if (other.isSetReview()) {
      this.review = other.review;
    }
    if (other.isSetTitle()) {
      this.title = other.title;
    }
    this.rating = other.rating;
    this.createdDttm = other.createdDttm;
  }

  public TRawReview deepCopy() {
    return new TRawReview(this);
  }

  @Override
  public void clear() {
    this.reviewId = null;
    this.review = null;
    this.title = null;
    setRatingIsSet(false);
    this.rating = 0;
    setCreatedDttmIsSet(false);
    this.createdDttm = 0;
  }

  public java.lang.String getReviewId() {
    return this.reviewId;
  }

  public TRawReview setReviewId(java.lang.String reviewId) {
    this.reviewId = reviewId;
    return this;
  }

  public void unsetReviewId() {
    this.reviewId = null;
  }

  /** Returns true if field reviewId is set (has been assigned a value) and false otherwise */
  public boolean isSetReviewId() {
    return this.reviewId != null;
  }

  public void setReviewIdIsSet(boolean value) {
    if (!value) {
      this.reviewId = null;
    }
  }

  public java.lang.String getReview() {
    return this.review;
  }

  public TRawReview setReview(java.lang.String review) {
    this.review = review;
    return this;
  }

  public void unsetReview() {
    this.review = null;
  }

  /** Returns true if field review is set (has been assigned a value) and false otherwise */
  public boolean isSetReview() {
    return this.review != null;
  }

  public void setReviewIsSet(boolean value) {
    if (!value) {
      this.review = null;
    }
  }

  public java.lang.String getTitle() {
    return this.title;
  }

  public TRawReview setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  public void unsetTitle() {
    this.title = null;
  }

  /** Returns true if field title is set (has been assigned a value) and false otherwise */
  public boolean isSetTitle() {
    return this.title != null;
  }

  public void setTitleIsSet(boolean value) {
    if (!value) {
      this.title = null;
    }
  }

  public int getRating() {
    return this.rating;
  }

  public TRawReview setRating(int rating) {
    this.rating = rating;
    setRatingIsSet(true);
    return this;
  }

  public void unsetRating() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RATING_ISSET_ID);
  }

  /** Returns true if field rating is set (has been assigned a value) and false otherwise */
  public boolean isSetRating() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RATING_ISSET_ID);
  }

  public void setRatingIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RATING_ISSET_ID, value);
  }

  public long getCreatedDttm() {
    return this.createdDttm;
  }

  public TRawReview setCreatedDttm(long createdDttm) {
    this.createdDttm = createdDttm;
    setCreatedDttmIsSet(true);
    return this;
  }

  public void unsetCreatedDttm() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATEDDTTM_ISSET_ID);
  }

  /** Returns true if field createdDttm is set (has been assigned a value) and false otherwise */
  public boolean isSetCreatedDttm() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATEDDTTM_ISSET_ID);
  }

  public void setCreatedDttmIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATEDDTTM_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case REVIEW_ID:
      if (value == null) {
        unsetReviewId();
      } else {
        setReviewId((java.lang.String)value);
      }
      break;

    case REVIEW:
      if (value == null) {
        unsetReview();
      } else {
        setReview((java.lang.String)value);
      }
      break;

    case TITLE:
      if (value == null) {
        unsetTitle();
      } else {
        setTitle((java.lang.String)value);
      }
      break;

    case RATING:
      if (value == null) {
        unsetRating();
      } else {
        setRating((java.lang.Integer)value);
      }
      break;

    case CREATED_DTTM:
      if (value == null) {
        unsetCreatedDttm();
      } else {
        setCreatedDttm((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case REVIEW_ID:
      return getReviewId();

    case REVIEW:
      return getReview();

    case TITLE:
      return getTitle();

    case RATING:
      return getRating();

    case CREATED_DTTM:
      return getCreatedDttm();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case REVIEW_ID:
      return isSetReviewId();
    case REVIEW:
      return isSetReview();
    case TITLE:
      return isSetTitle();
    case RATING:
      return isSetRating();
    case CREATED_DTTM:
      return isSetCreatedDttm();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TRawReview)
      return this.equals((TRawReview)that);
    return false;
  }

  public boolean equals(TRawReview that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_reviewId = true && this.isSetReviewId();
    boolean that_present_reviewId = true && that.isSetReviewId();
    if (this_present_reviewId || that_present_reviewId) {
      if (!(this_present_reviewId && that_present_reviewId))
        return false;
      if (!this.reviewId.equals(that.reviewId))
        return false;
    }

    boolean this_present_review = true && this.isSetReview();
    boolean that_present_review = true && that.isSetReview();
    if (this_present_review || that_present_review) {
      if (!(this_present_review && that_present_review))
        return false;
      if (!this.review.equals(that.review))
        return false;
    }

    boolean this_present_title = true && this.isSetTitle();
    boolean that_present_title = true && that.isSetTitle();
    if (this_present_title || that_present_title) {
      if (!(this_present_title && that_present_title))
        return false;
      if (!this.title.equals(that.title))
        return false;
    }

    boolean this_present_rating = true;
    boolean that_present_rating = true;
    if (this_present_rating || that_present_rating) {
      if (!(this_present_rating && that_present_rating))
        return false;
      if (this.rating != that.rating)
        return false;
    }

    boolean this_present_createdDttm = true;
    boolean that_present_createdDttm = true;
    if (this_present_createdDttm || that_present_createdDttm) {
      if (!(this_present_createdDttm && that_present_createdDttm))
        return false;
      if (this.createdDttm != that.createdDttm)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetReviewId()) ? 131071 : 524287);
    if (isSetReviewId())
      hashCode = hashCode * 8191 + reviewId.hashCode();

    hashCode = hashCode * 8191 + ((isSetReview()) ? 131071 : 524287);
    if (isSetReview())
      hashCode = hashCode * 8191 + review.hashCode();

    hashCode = hashCode * 8191 + ((isSetTitle()) ? 131071 : 524287);
    if (isSetTitle())
      hashCode = hashCode * 8191 + title.hashCode();

    hashCode = hashCode * 8191 + rating;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createdDttm);

    return hashCode;
  }

  @Override
  public int compareTo(TRawReview other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetReviewId()).compareTo(other.isSetReviewId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReviewId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reviewId, other.reviewId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReview()).compareTo(other.isSetReview());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReview()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.review, other.review);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTitle()).compareTo(other.isSetTitle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTitle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.title, other.title);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRating()).compareTo(other.isSetRating());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRating()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rating, other.rating);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCreatedDttm()).compareTo(other.isSetCreatedDttm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreatedDttm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createdDttm, other.createdDttm);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TRawReview(");
    boolean first = true;

    sb.append("reviewId:");
    if (this.reviewId == null) {
      sb.append("null");
    } else {
      sb.append(this.reviewId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("review:");
    if (this.review == null) {
      sb.append("null");
    } else {
      sb.append(this.review);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("title:");
    if (this.title == null) {
      sb.append("null");
    } else {
      sb.append(this.title);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rating:");
    sb.append(this.rating);
    first = false;
    if (!first) sb.append(", ");
    sb.append("createdDttm:");
    sb.append(this.createdDttm);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TRawReviewStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TRawReviewStandardScheme getScheme() {
      return new TRawReviewStandardScheme();
    }
  }

  private static class TRawReviewStandardScheme extends org.apache.thrift.scheme.StandardScheme<TRawReview> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TRawReview struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REVIEW_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.reviewId = iprot.readString();
              struct.setReviewIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // REVIEW
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.review = iprot.readString();
              struct.setReviewIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TITLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.title = iprot.readString();
              struct.setTitleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // RATING
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.rating = iprot.readI32();
              struct.setRatingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CREATED_DTTM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createdDttm = iprot.readI64();
              struct.setCreatedDttmIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TRawReview struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.reviewId != null) {
        oprot.writeFieldBegin(REVIEW_ID_FIELD_DESC);
        oprot.writeString(struct.reviewId);
        oprot.writeFieldEnd();
      }
      if (struct.review != null) {
        oprot.writeFieldBegin(REVIEW_FIELD_DESC);
        oprot.writeString(struct.review);
        oprot.writeFieldEnd();
      }
      if (struct.title != null) {
        oprot.writeFieldBegin(TITLE_FIELD_DESC);
        oprot.writeString(struct.title);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(RATING_FIELD_DESC);
      oprot.writeI32(struct.rating);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CREATED_DTTM_FIELD_DESC);
      oprot.writeI64(struct.createdDttm);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TRawReviewTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TRawReviewTupleScheme getScheme() {
      return new TRawReviewTupleScheme();
    }
  }

  private static class TRawReviewTupleScheme extends org.apache.thrift.scheme.TupleScheme<TRawReview> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TRawReview struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetReviewId()) {
        optionals.set(0);
      }
      if (struct.isSetReview()) {
        optionals.set(1);
      }
      if (struct.isSetTitle()) {
        optionals.set(2);
      }
      if (struct.isSetRating()) {
        optionals.set(3);
      }
      if (struct.isSetCreatedDttm()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetReviewId()) {
        oprot.writeString(struct.reviewId);
      }
      if (struct.isSetReview()) {
        oprot.writeString(struct.review);
      }
      if (struct.isSetTitle()) {
        oprot.writeString(struct.title);
      }
      if (struct.isSetRating()) {
        oprot.writeI32(struct.rating);
      }
      if (struct.isSetCreatedDttm()) {
        oprot.writeI64(struct.createdDttm);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TRawReview struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.reviewId = iprot.readString();
        struct.setReviewIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.review = iprot.readString();
        struct.setReviewIsSet(true);
      }
      if (incoming.get(2)) {
        struct.title = iprot.readString();
        struct.setTitleIsSet(true);
      }
      if (incoming.get(3)) {
        struct.rating = iprot.readI32();
        struct.setRatingIsSet(true);
      }
      if (incoming.get(4)) {
        struct.createdDttm = iprot.readI64();
        struct.setCreatedDttmIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

