/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bk.thesis.data.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-07-20")
public class TReviewMeta implements org.apache.thrift.TBase<TReviewMeta, TReviewMeta._Fields>, java.io.Serializable, Cloneable, Comparable<TReviewMeta> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TReviewMeta");

  private static final org.apache.thrift.protocol.TField LASTEST_DTTM_FIELD_DESC = new org.apache.thrift.protocol.TField("lastestDttm", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField LASTEST_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("lastestId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField LENGTH_FIELD_DESC = new org.apache.thrift.protocol.TField("length", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TReviewMetaStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TReviewMetaTupleSchemeFactory();

  public long lastestDttm; // required
  public java.lang.String lastestId; // required
  public int length; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LASTEST_DTTM((short)1, "lastestDttm"),
    LASTEST_ID((short)2, "lastestId"),
    LENGTH((short)3, "length");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LASTEST_DTTM
          return LASTEST_DTTM;
        case 2: // LASTEST_ID
          return LASTEST_ID;
        case 3: // LENGTH
          return LENGTH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LASTESTDTTM_ISSET_ID = 0;
  private static final int __LENGTH_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LASTEST_DTTM, new org.apache.thrift.meta_data.FieldMetaData("lastestDttm", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.LASTEST_ID, new org.apache.thrift.meta_data.FieldMetaData("lastestId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LENGTH, new org.apache.thrift.meta_data.FieldMetaData("length", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TReviewMeta.class, metaDataMap);
  }

  public TReviewMeta() {
  }

  public TReviewMeta(
    long lastestDttm,
    java.lang.String lastestId,
    int length)
  {
    this();
    this.lastestDttm = lastestDttm;
    setLastestDttmIsSet(true);
    this.lastestId = lastestId;
    this.length = length;
    setLengthIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TReviewMeta(TReviewMeta other) {
    __isset_bitfield = other.__isset_bitfield;
    this.lastestDttm = other.lastestDttm;
    if (other.isSetLastestId()) {
      this.lastestId = other.lastestId;
    }
    this.length = other.length;
  }

  public TReviewMeta deepCopy() {
    return new TReviewMeta(this);
  }

  @Override
  public void clear() {
    setLastestDttmIsSet(false);
    this.lastestDttm = 0;
    this.lastestId = null;
    setLengthIsSet(false);
    this.length = 0;
  }

  public long getLastestDttm() {
    return this.lastestDttm;
  }

  public TReviewMeta setLastestDttm(long lastestDttm) {
    this.lastestDttm = lastestDttm;
    setLastestDttmIsSet(true);
    return this;
  }

  public void unsetLastestDttm() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LASTESTDTTM_ISSET_ID);
  }

  /** Returns true if field lastestDttm is set (has been assigned a value) and false otherwise */
  public boolean isSetLastestDttm() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LASTESTDTTM_ISSET_ID);
  }

  public void setLastestDttmIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LASTESTDTTM_ISSET_ID, value);
  }

  public java.lang.String getLastestId() {
    return this.lastestId;
  }

  public TReviewMeta setLastestId(java.lang.String lastestId) {
    this.lastestId = lastestId;
    return this;
  }

  public void unsetLastestId() {
    this.lastestId = null;
  }

  /** Returns true if field lastestId is set (has been assigned a value) and false otherwise */
  public boolean isSetLastestId() {
    return this.lastestId != null;
  }

  public void setLastestIdIsSet(boolean value) {
    if (!value) {
      this.lastestId = null;
    }
  }

  public int getLength() {
    return this.length;
  }

  public TReviewMeta setLength(int length) {
    this.length = length;
    setLengthIsSet(true);
    return this;
  }

  public void unsetLength() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LENGTH_ISSET_ID);
  }

  /** Returns true if field length is set (has been assigned a value) and false otherwise */
  public boolean isSetLength() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LENGTH_ISSET_ID);
  }

  public void setLengthIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LENGTH_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case LASTEST_DTTM:
      if (value == null) {
        unsetLastestDttm();
      } else {
        setLastestDttm((java.lang.Long)value);
      }
      break;

    case LASTEST_ID:
      if (value == null) {
        unsetLastestId();
      } else {
        setLastestId((java.lang.String)value);
      }
      break;

    case LENGTH:
      if (value == null) {
        unsetLength();
      } else {
        setLength((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LASTEST_DTTM:
      return getLastestDttm();

    case LASTEST_ID:
      return getLastestId();

    case LENGTH:
      return getLength();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LASTEST_DTTM:
      return isSetLastestDttm();
    case LASTEST_ID:
      return isSetLastestId();
    case LENGTH:
      return isSetLength();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TReviewMeta)
      return this.equals((TReviewMeta)that);
    return false;
  }

  public boolean equals(TReviewMeta that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_lastestDttm = true;
    boolean that_present_lastestDttm = true;
    if (this_present_lastestDttm || that_present_lastestDttm) {
      if (!(this_present_lastestDttm && that_present_lastestDttm))
        return false;
      if (this.lastestDttm != that.lastestDttm)
        return false;
    }

    boolean this_present_lastestId = true && this.isSetLastestId();
    boolean that_present_lastestId = true && that.isSetLastestId();
    if (this_present_lastestId || that_present_lastestId) {
      if (!(this_present_lastestId && that_present_lastestId))
        return false;
      if (!this.lastestId.equals(that.lastestId))
        return false;
    }

    boolean this_present_length = true;
    boolean that_present_length = true;
    if (this_present_length || that_present_length) {
      if (!(this_present_length && that_present_length))
        return false;
      if (this.length != that.length)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(lastestDttm);

    hashCode = hashCode * 8191 + ((isSetLastestId()) ? 131071 : 524287);
    if (isSetLastestId())
      hashCode = hashCode * 8191 + lastestId.hashCode();

    hashCode = hashCode * 8191 + length;

    return hashCode;
  }

  @Override
  public int compareTo(TReviewMeta other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetLastestDttm()).compareTo(other.isSetLastestDttm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastestDttm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastestDttm, other.lastestDttm);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLastestId()).compareTo(other.isSetLastestId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastestId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastestId, other.lastestId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLength()).compareTo(other.isSetLength());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLength()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.length, other.length);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TReviewMeta(");
    boolean first = true;

    sb.append("lastestDttm:");
    sb.append(this.lastestDttm);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastestId:");
    if (this.lastestId == null) {
      sb.append("null");
    } else {
      sb.append(this.lastestId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("length:");
    sb.append(this.length);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TReviewMetaStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TReviewMetaStandardScheme getScheme() {
      return new TReviewMetaStandardScheme();
    }
  }

  private static class TReviewMetaStandardScheme extends org.apache.thrift.scheme.StandardScheme<TReviewMeta> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TReviewMeta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LASTEST_DTTM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastestDttm = iprot.readI64();
              struct.setLastestDttmIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LASTEST_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lastestId = iprot.readString();
              struct.setLastestIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LENGTH
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.length = iprot.readI32();
              struct.setLengthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TReviewMeta struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(LASTEST_DTTM_FIELD_DESC);
      oprot.writeI64(struct.lastestDttm);
      oprot.writeFieldEnd();
      if (struct.lastestId != null) {
        oprot.writeFieldBegin(LASTEST_ID_FIELD_DESC);
        oprot.writeString(struct.lastestId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LENGTH_FIELD_DESC);
      oprot.writeI32(struct.length);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TReviewMetaTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TReviewMetaTupleScheme getScheme() {
      return new TReviewMetaTupleScheme();
    }
  }

  private static class TReviewMetaTupleScheme extends org.apache.thrift.scheme.TupleScheme<TReviewMeta> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TReviewMeta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLastestDttm()) {
        optionals.set(0);
      }
      if (struct.isSetLastestId()) {
        optionals.set(1);
      }
      if (struct.isSetLength()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetLastestDttm()) {
        oprot.writeI64(struct.lastestDttm);
      }
      if (struct.isSetLastestId()) {
        oprot.writeString(struct.lastestId);
      }
      if (struct.isSetLength()) {
        oprot.writeI32(struct.length);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TReviewMeta struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.lastestDttm = iprot.readI64();
        struct.setLastestDttmIsSet(true);
      }
      if (incoming.get(1)) {
        struct.lastestId = iprot.readString();
        struct.setLastestIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.length = iprot.readI32();
        struct.setLengthIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

