/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bk.thesis.data.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-07-20")
public class TTags implements org.apache.thrift.TBase<TTags, TTags._Fields>, java.io.Serializable, Cloneable, Comparable<TTags> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TTags");

  private static final org.apache.thrift.protocol.TField PRODUCT_TAG_FIELD_DESC = new org.apache.thrift.protocol.TField("productTag", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField BRANCH_TAG_FIELD_DESC = new org.apache.thrift.protocol.TField("branchTag", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField DETAIL_TAG_FIELD_DESC = new org.apache.thrift.protocol.TField("detailTag", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TTagsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TTagsTupleSchemeFactory();

  public int productTag; // required
  public int branchTag; // required
  public int detailTag; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRODUCT_TAG((short)1, "productTag"),
    BRANCH_TAG((short)2, "branchTag"),
    DETAIL_TAG((short)3, "detailTag");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRODUCT_TAG
          return PRODUCT_TAG;
        case 2: // BRANCH_TAG
          return BRANCH_TAG;
        case 3: // DETAIL_TAG
          return DETAIL_TAG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PRODUCTTAG_ISSET_ID = 0;
  private static final int __BRANCHTAG_ISSET_ID = 1;
  private static final int __DETAILTAG_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRODUCT_TAG, new org.apache.thrift.meta_data.FieldMetaData("productTag", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.BRANCH_TAG, new org.apache.thrift.meta_data.FieldMetaData("branchTag", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DETAIL_TAG, new org.apache.thrift.meta_data.FieldMetaData("detailTag", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TTags.class, metaDataMap);
  }

  public TTags() {
  }

  public TTags(
    int productTag,
    int branchTag,
    int detailTag)
  {
    this();
    this.productTag = productTag;
    setProductTagIsSet(true);
    this.branchTag = branchTag;
    setBranchTagIsSet(true);
    this.detailTag = detailTag;
    setDetailTagIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TTags(TTags other) {
    __isset_bitfield = other.__isset_bitfield;
    this.productTag = other.productTag;
    this.branchTag = other.branchTag;
    this.detailTag = other.detailTag;
  }

  public TTags deepCopy() {
    return new TTags(this);
  }

  @Override
  public void clear() {
    setProductTagIsSet(false);
    this.productTag = 0;
    setBranchTagIsSet(false);
    this.branchTag = 0;
    setDetailTagIsSet(false);
    this.detailTag = 0;
  }

  public int getProductTag() {
    return this.productTag;
  }

  public TTags setProductTag(int productTag) {
    this.productTag = productTag;
    setProductTagIsSet(true);
    return this;
  }

  public void unsetProductTag() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PRODUCTTAG_ISSET_ID);
  }

  /** Returns true if field productTag is set (has been assigned a value) and false otherwise */
  public boolean isSetProductTag() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PRODUCTTAG_ISSET_ID);
  }

  public void setProductTagIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PRODUCTTAG_ISSET_ID, value);
  }

  public int getBranchTag() {
    return this.branchTag;
  }

  public TTags setBranchTag(int branchTag) {
    this.branchTag = branchTag;
    setBranchTagIsSet(true);
    return this;
  }

  public void unsetBranchTag() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BRANCHTAG_ISSET_ID);
  }

  /** Returns true if field branchTag is set (has been assigned a value) and false otherwise */
  public boolean isSetBranchTag() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BRANCHTAG_ISSET_ID);
  }

  public void setBranchTagIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BRANCHTAG_ISSET_ID, value);
  }

  public int getDetailTag() {
    return this.detailTag;
  }

  public TTags setDetailTag(int detailTag) {
    this.detailTag = detailTag;
    setDetailTagIsSet(true);
    return this;
  }

  public void unsetDetailTag() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DETAILTAG_ISSET_ID);
  }

  /** Returns true if field detailTag is set (has been assigned a value) and false otherwise */
  public boolean isSetDetailTag() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DETAILTAG_ISSET_ID);
  }

  public void setDetailTagIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DETAILTAG_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PRODUCT_TAG:
      if (value == null) {
        unsetProductTag();
      } else {
        setProductTag((java.lang.Integer)value);
      }
      break;

    case BRANCH_TAG:
      if (value == null) {
        unsetBranchTag();
      } else {
        setBranchTag((java.lang.Integer)value);
      }
      break;

    case DETAIL_TAG:
      if (value == null) {
        unsetDetailTag();
      } else {
        setDetailTag((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PRODUCT_TAG:
      return getProductTag();

    case BRANCH_TAG:
      return getBranchTag();

    case DETAIL_TAG:
      return getDetailTag();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PRODUCT_TAG:
      return isSetProductTag();
    case BRANCH_TAG:
      return isSetBranchTag();
    case DETAIL_TAG:
      return isSetDetailTag();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TTags)
      return this.equals((TTags)that);
    return false;
  }

  public boolean equals(TTags that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_productTag = true;
    boolean that_present_productTag = true;
    if (this_present_productTag || that_present_productTag) {
      if (!(this_present_productTag && that_present_productTag))
        return false;
      if (this.productTag != that.productTag)
        return false;
    }

    boolean this_present_branchTag = true;
    boolean that_present_branchTag = true;
    if (this_present_branchTag || that_present_branchTag) {
      if (!(this_present_branchTag && that_present_branchTag))
        return false;
      if (this.branchTag != that.branchTag)
        return false;
    }

    boolean this_present_detailTag = true;
    boolean that_present_detailTag = true;
    if (this_present_detailTag || that_present_detailTag) {
      if (!(this_present_detailTag && that_present_detailTag))
        return false;
      if (this.detailTag != that.detailTag)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + productTag;

    hashCode = hashCode * 8191 + branchTag;

    hashCode = hashCode * 8191 + detailTag;

    return hashCode;
  }

  @Override
  public int compareTo(TTags other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetProductTag()).compareTo(other.isSetProductTag());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProductTag()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.productTag, other.productTag);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBranchTag()).compareTo(other.isSetBranchTag());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBranchTag()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.branchTag, other.branchTag);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDetailTag()).compareTo(other.isSetDetailTag());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDetailTag()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.detailTag, other.detailTag);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TTags(");
    boolean first = true;

    sb.append("productTag:");
    sb.append(this.productTag);
    first = false;
    if (!first) sb.append(", ");
    sb.append("branchTag:");
    sb.append(this.branchTag);
    first = false;
    if (!first) sb.append(", ");
    sb.append("detailTag:");
    sb.append(this.detailTag);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TTagsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TTagsStandardScheme getScheme() {
      return new TTagsStandardScheme();
    }
  }

  private static class TTagsStandardScheme extends org.apache.thrift.scheme.StandardScheme<TTags> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TTags struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRODUCT_TAG
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.productTag = iprot.readI32();
              struct.setProductTagIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BRANCH_TAG
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.branchTag = iprot.readI32();
              struct.setBranchTagIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DETAIL_TAG
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.detailTag = iprot.readI32();
              struct.setDetailTagIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TTags struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PRODUCT_TAG_FIELD_DESC);
      oprot.writeI32(struct.productTag);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BRANCH_TAG_FIELD_DESC);
      oprot.writeI32(struct.branchTag);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DETAIL_TAG_FIELD_DESC);
      oprot.writeI32(struct.detailTag);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TTagsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TTagsTupleScheme getScheme() {
      return new TTagsTupleScheme();
    }
  }

  private static class TTagsTupleScheme extends org.apache.thrift.scheme.TupleScheme<TTags> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TTags struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetProductTag()) {
        optionals.set(0);
      }
      if (struct.isSetBranchTag()) {
        optionals.set(1);
      }
      if (struct.isSetDetailTag()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetProductTag()) {
        oprot.writeI32(struct.productTag);
      }
      if (struct.isSetBranchTag()) {
        oprot.writeI32(struct.branchTag);
      }
      if (struct.isSetDetailTag()) {
        oprot.writeI32(struct.detailTag);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TTags struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.productTag = iprot.readI32();
        struct.setProductTagIsSet(true);
      }
      if (incoming.get(1)) {
        struct.branchTag = iprot.readI32();
        struct.setBranchTagIsSet(true);
      }
      if (incoming.get(2)) {
        struct.detailTag = iprot.readI32();
        struct.setDetailTagIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

