/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bk.thesis.data.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ETagType implements org.apache.thrift.TEnum {
  PRODUCT(0),
  BRANCH(1),
  DETAIL(2);

  private final int value;

  private ETagType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ETagType findByValue(int value) { 
    switch (value) {
      case 0:
        return PRODUCT;
      case 1:
        return BRANCH;
      case 2:
        return DETAIL;
      default:
        return null;
    }
  }
}
